springdoc:
  # Swagger? ??? ?? API? ??? ??? ??
  packages-to-scan: com.ohgiraffers.restapi

  #consumes : Swagger? ????? ???? ??? "Content-Type(??? UTF-8)"
  default-consumes-media-type: application/json;charset=UTF-8

  #produces :  Swagger? ????? ???? ??? "Content-Type(??? UTF-8)"
  default-produces-media-type: application/json;charset=UTF-8